name: GitHub Actions Demo

on: [push]

jobs:
  embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Embedding files
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          deno run -A .github/scripts/embedding.ts
