name: GitHub Actions Demo

on: [push]

jobs:
  embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check if namespace is created
        run: |
          echo ${{ secrets.TURBOPUFFER_API_KEY }}