name: GitHub Actions Demo

on: [push]

jobs:
  embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Add embeddings
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo $REPO_NAME
