name: Delete Namespace

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  delete-namespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.13' 

      - name: Install dependencies
        run: pip install -r .github/delete-namespace-requirements.txt

      - name: Delete Namespace
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
        run: python .github/scripts/delete-namespace.py
