name: Embed files

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  embedding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup get changed files
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          separator: ","

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          pip install -r .github/requirements.txt

      - name: Embedding files
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          python .github/scripts/embed_files.py
